### ISSUE TITLE
Dataset links not working

### ISSUE THREAD

**Issue by chiayewken** [dinobby/ZS-BERT#2]
Thank you for your work!
Currently, the google drive links for the datasets requires access, could you change the sharing permissions?

https://drive.google.com/file/d/1Ju5ngSL9Bpb7K0br11ocyPWzDA8N5-9v/view?usp=sharing
https://drive.google.com/file/d/1q_q1TA-c_xSCj0-CscWxmvvExr46ZcQS/view?usp=sharing

**Comment by dinobby** [comment]
Hi chiayew!
Really sorry for the late reply. 
The datasets should be able to download by the provided link now!

**Comment by chiayewken** [comment]
Thanks, the access is granted for the links now.
